services:
  - type: web
    name: repair-store-ks
    env: static
    buildCommand: echo "No build required for static site"
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache