services:
  - type: web
    name: repair-store-ks
    env: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /**/*.css
        name: Content-Type
        value: text/css; charset=utf-8
      - path: /**/*.js
        name: Content-Type
        value: application/javascript; charset=utf-8
      - path: /**/*.html
        name: Content-Type
        value: text/html; charset=utf-8